stages:

    profile:
        cmd: python3 src/profiling.py assets/data/raw/
        deps:
        - assets/data/raw
        - src/profiling.py
        - src/profile.yaml
        - src/config.py
        outs:
        - assets/profile
        params:
        - profile.dataset

    clean:
        cmd: python3 src/clean.py assets/data/raw/
        deps:
        - assets/data/raw
        - assets/profile
        - src/clean.py
        - src/config.py
        outs:
        - assets/data/cleaned
        params:
        - clean.combine_files
        - clean.percentage_zeros_threshold
        - clean.correlation_metric
        - clean.input_max_correlation_threshold

    featurize:
        cmd: python3 src/featurize.py assets/data/cleaned/
        deps:
        - assets/data/cleaned
        - src/featurize.py
        - src/config.py
        outs:
        - assets/data/featurized
        - assets/data/input_columns.csv
        params:
        - featurize.features
        - featurize.add_rolling_features
        - featurize.rolling_window_size
        - featurize.remove_features

    scale:
        cmd: python3 src/scale.py assets/data/featurized/
        deps:
        - assets/data/featurized
        - src/scale.py
        - src/config.py
        outs:
        - assets/data/scaled
        params:
        - scale.input

    sequentialize:
        cmd: python3 src/sequentialize.py assets/data/scaled/
        deps:
        - assets/data/scaled
        - src/sequentialize.py
        - src/preprocess_utils.py
        - src/config.py
        outs:
        - assets/data/sequentialized
        params:
        - sequentialize.window_size
        - sequentialize.overlap
        - sequentialize.shuffle_samples
        - train.learning_method

    combine:
        cmd: python3 src/combine.py assets/data/sequentialized/
        deps:
        - assets/data/sequentialized
        - src/combine.py
        - src/config.py
        outs:
        - assets/data/combined

    train:
        cmd: python3 src/train.py assets/data/combined/X.npz
        deps:
        - assets/data/combined
        - src/train.py
        - src/config.py
        outs:
        - assets/models
        params:
        - train.learning_method
        - train.n_clusters

    visualize:
        cmd: python3 src/visualize.py assets/models/model.h5 assets/data/combined/X.npz 
        deps:
        - assets/data/combined
        - assets/models/model.h5
        - src/visualize.py
        - src/config.py
