profile:
    dataset: split_by_pn
    # dataset: half_size

clean:
    combine_files: False
    percentage_zeros_threshold: 1.0
    correlation_metric: pearson
    input_max_correlation_threshold: 1.0

featurize:
    features:
        # TN
        # - TN
        # - PN
        # - Axis_X_Real_Position
        # - Axis_X_Target_Position
        # - Axis_Y_Real_Position
        # - Axis_Y_Target_Position
        # - Axis_Z_Real_Position
        # - Axis_Z_Target_Position
        - Spindle_Torque
    add_rolling_features: True
    rolling_window_size: 4400
    remove_features:
        # - TN
        - Spindle_Torque
        # - PN
        # - Axis_X_Real_Position
        # - Axis_X_Target_Position
        # - Axis_Y_Real_Position
        # - Axis_Y_Target_Position
        # - Axis_Z_Real_Position
        # - Axis_Z_Target_Position
        # - TN
        # - Axis_Y_Position_Diff
        # - Axis_Z_Position_Diff
        # - Axis_B_Position_Diff
        # - Abs_Sum_Position_Diff

split:
    train_split: 0.7
    shuffle_files: False

scale:
    input:

sequentialize:
    window_size: 1
    overlap: 0
    shuffle_samples: False

train:
    learning_method: kmeans
    # learning_method: timeserieskmeans
    n_clusters: 2

visualize:
