profile:
    dataset: medium_10th
    # dataset: every_10th_PN40
    # dataset: half_size

clean:
    combine_files: False
    percentage_zeros_threshold: 1.0
    correlation_metric: pearson
    input_max_correlation_threshold: 1.0

featurize:
    features:
        # - TN
        # - PN
        # - Axis_X_Real_Position
        # - Axis_X_Target_Position
        # - Axis_Y_Real_Position
        # - Axis_Y_Target_Position
        # - Axis_Z_Real_Position
        # - Axis_Z_Target_Position
        # - Spindle_Torque
    add_rolling_features: True
    rolling_window_size: 220
    remove_features:
        # - TN
        # - Spindle_Torque
        # - PN
        # - Axis_X_Real_Position
        # - Axis_X_Target_Position
        # - Axis_Y_Real_Position
        # - Axis_Y_Target_Position
        # - Axis_Z_Real_Position
        # - Axis_Z_Target_Position
        # - Axis_Y_Position_Diff
        # - Axis_Z_Position_Diff
        # - Axis_B_Position_Diff
        # - Abs_Sum_Position_Diff

scale:
    input:
    # input: minmax

sequentialize:
    window_size: 1
    overlap: 0
    shuffle_samples: False
    pca: True

train:
    # learning_method: kmeans
    # learning_method: timeserieskmeans
    learning_method: hierarchical
    n_clusters: 2

visualize:
