profile:
    dataset: automotive

clean:
    combine_files: True
    percentage_zeros_threshold: 1.0
    correlation_metric: pearson
    input_max_correlation_threshold: 1.0

featurize:
    features:
    add_rolling_features: False
    rolling_window_size: 100
    remove_features:
        # - Axis_Y_Position_Diff
        # - Axis_Z_Position_Diff
        # - Axis_B_Position_Diff
        # - Abs_Sum_Position_Diff

split:
    train_split: 0.7
    shuffle_files: False

scale:
    input: minmax

sequentialize:
    window_size: 4400
    overlap: 0
    shuffle_samples: False

train:
    learning_method: timeserieskmeans
    n_clusters: 3

visualize:
